---
- name: Create directory for ansible custom facts
  become: true
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d

- name: Create facts file from template
  become: true
  ansible.builtin.template:
    src: autorestic.fact.j2
    dest: /etc/ansible/facts.d/autorestic.fact
    mode: '0755'
  register: autorestic__register_facts

- name: Re-read facts after adding custom fact
  become: true
  ansible.builtin.setup:
    filter: ansible_local

- block:
    - name: get latest GH autorestic version
      ansible.builtin.uri:
        url: https://api.github.com/repos/cupcakearmy/autorestic/releases/latest
        url_username: "{{ github_api_user | default (omit) }}"
        url_password: "{{ github_api_pass | default (omit) }}"
        return_content: true
        force_basic_auth: "{{ github_api_auth | default (omit) }}"
      register: release_version_registered
      when: autorestic_download_latest_ver

    - name: set autorestic version (latest)
      ansible.builtin.set_fact:
        autorestic_ver: "{{ release_version_registered.json.tag_name|regex_replace('v') }}"
      when: autorestic_download_latest_ver

    - name: set autorestic version (pinned)
      ansible.builtin.set_fact:
        autorestic_ver: "{{ autorestic_pinned_ver }}"
      when: not autorestic_download_latest_ver

- name: local autorestic version
  ansible.builtin.debug:
    var: ansible_local.autorestic

- name: github Version
  ansible.builtin.debug:
    var: autorestic_ver
