# code: language=ansible
---
- name: Restic versioncheck
  ansible.builtin.include_tasks: restic_versioncheck.yml

- name: Autorestic versioncheck
  ansible.builtin.include_tasks: autorestic_versioncheck.yml

- name: Prepare install
  ansible.builtin.include_tasks: prepare.yml

- name: Install autorestic
  ansible.builtin.include_tasks: install_autorestic.yml

- name: Install restic
  ansible.builtin.include_tasks: install_restic.yml

# - name: configure autorestic
#   include_tasks: configure.yml
